#build stage
FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /go/src/app
COPY . .
RUN go get -d -v ./...
RUN go build -o /go/bin/app -v ./...

#final stage
FROM nginx:1.25.2-alpine
RUN apk --no-cache add ca-certificates curl
COPY --from=builder /go/bin/app /app
COPY ./ /
COPY configs/ /
RUN chmod +x /entrypoint.sh
ENTRYPOINT /entrypoint.sh
LABEL Name=go-rest Version=0.0.1
RUN curl -sSL https://get.docker.com/
VOLUME /data
USER root
EXPOSE 9090