pipeline {
    agent any
    parameters {
        string(name: 'ImageRegistry', defaultValue: 'registry.i-3.my.id:5000', description: 'Image Registry address')
        string(name: 'OcpCluster', defaultValue: 'https://api.lab.i3datacenter.my.id:6443', description: 'Openshift Cluster API')
        choice(name: 'ocpProject', choices: 'devsecops-demo', description: 'Project where app to be deployed')
        choice(name: 'manifestFile', choices: ['dev-deployment.yaml', 'prod-deployment.yaml'], description: 'env where app to be deployed')
        choice(name: 'appEndpoint', choices: ['gosip-app-prod.apps.lab.i3datacenter.my.id', 'gosip-app-dev.apps.lab.i3datacenter.my.id'], description: 'App endpoint for zap to scan')
        string(name: 'OcpProject', defaultValue: 'devsecops-demo', description: 'Openshift Cluster API')
    }
    environment {
        REGISTRY_CRED = credentials('i3-internal-registry-cred')
        CLUSTER_TKN = credentials('i3-ocp-deployer-tkn')
    }
    stages {
        stage('Sonarqube - Static application security testing process') {
            steps {
                sh 'cd app/'
                sh '/home/jenkins/sonar-scanner/sonar-scanner/bin/sonar-scanner'      
            }
        }
        stage('Build Container Image') {
            steps {
                sh('docker image rm $ImageRegistry/devsecops:v${BUILD_NUMBER} || echo "No existing image found"')
                sh('docker build --no-cache -t $ImageRegistry/devsecops:v${BUILD_NUMBER} -f app/deploy/Dockerfile app/')
            }
        }
        stage('Trivy - Container security scan') {
            steps {
                sh 'cd app/deploy'
                sh 'touch /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretpython.html'
                sh 'trivy image --format template --template "@html.tpl" -o /var/www/html/trivy/pipeline${BUILD_NUMBER}/reportimagesecretpython.html --exit-code 0 --severity HIGH,CRITICAL ${ImageRegistry}/devsecops:v${BUILD_NUMBER}'
            }
        }
        stage('Push Image to nexus') {
            steps {
                sh('echo "$REGISTRY_CRED_PSW" | docker login $ImageRegistry -u $REGISTRY_CRED_USR --password-stdin')
                sh('docker push $ImageRegistry/devsecops:v${BUILD_NUMBER}')
                sh('docker rmi $ImageRegistry/devsecops:v${BUILD_NUMBER}') 
            }
        }
        stage('Deploy app to Staging env') {
            steps {
                sh('cd app/deploy/manifest')
                sh('echo "$CLUSTER_CRED_PSW" | oc login --server=$OpenshiftCluster -u $CLUSTER_CRED_USR --password-stdin')
                sh('oc login --token=$CLUSTER_TKN --server=$OcpCluster')
                sh('oc project $ocpProject && oc create $manifestFile')
                sh('sleep 30s && oc get all')
            }
        }
        stage('Zap Proxy - Dynamic application security testing process') {
            steps {
                    sh """
                    docker run --rm -v /zap:/zap/wrk:rw -v /opt/hosts_zap:/etc/hosts -t ictu/zap2docker-weekly zap-baseline.py -I -j \
                    -t http://$appEndpoint \
                    -r reportzap.html \
                    -J reportzap.json \
                    -g reportzap.conf \
                    --hook=/zap/auth_hook.py \
                    -z "auth.loginurl=http://$appEndpoint/login \
                        auth.username="user" \
                        auth.password="password""
                    mkdir /var/www/html/zapReport/pipeline${BUILD_NUMBER}/
                    cp /zap/* /var/www/html/zapReport/pipeline${BUILD_NUMBER}/
                    rm -rf /zap/*
                    """
            }
        }
        stage('Clean up cred') {
            steps {
                sh('docker logout')
                sh('oc logout')
            }
        }
    }
}