pipeline {
    agent any
    parameters {
        string(name: 'Dockerfile', defaultValue: 'app/py-sample/deploy/Dockerfile', description: 'Dockerfile path for buildning the app')
        string(name: 'SqProject', defaultValue: 'devsecops-test-personal', description: 'SQ project key based on your project')
        string(name: 'SqServer', defaultValue: 'https://student00.lab.i-3.my.id:9000', description: 'SQ server address')
        string(name: 'ImageRegistry', defaultValue: 'registry.i-3.my.id:5000', description: 'Image Registry address')
        string(name: 'OcpCluster', defaultValue: 'https://api.lab.i3datacenter.my.id:6443', description: 'Openshift Cluster API')
        string(name: 'ocpProject', defaultValue: 'devsecops-demo', description: 'Project where app to be deployed')
        string(name: 'manifestFile', defaultValue: './dev-deployment.yaml', description: 'Path of manifest file to be deployed') 
        string(name: 'appEndpoint', defaultValue: 'gosip-app-dev.apps.lab.i3datacenter.my.id', description: 'Application address that exposed by route for Dynamic Application Security Test')    
    }
    environment {
        REGISTRY_CRED = credentials('i3-internal-registry-cred')
        CLUSTER_TKN = credentials('i3-ocp-deployer-tkn')
        SQ_TKN= credentials('i3-sq-tkn')
    }
    stages {
        stage('Sonarqube - Static application security testing process') {
            steps {
                sh 'cd app/py-sample/'
                sh 'sonar-scanner \
                    -Dsonar.projectKey=$SqProject \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=$SqServer \
                    -Dsonar.login=$SQ_TKN'      
            }
        }
        stage('Build Container Image') {
            steps {
                sh('docker image rm $ImageRegistry/devsecops:v${BUILD_NUMBER} || echo "No existing image found"')
                sh('docker build --no-cache -t $ImageRegistry/devsecops:v${BUILD_NUMBER} -f $Dockerfile app/py-sample')
            }
        }
        stage('Trivy - Container security scan') {
            steps {
                sh('cd app/py-sample/deploy')
                sh('touch /tmp/pipeline-report/trivy-pipeline${BUILD_NUMBER}-report.html')
                sh('trivy image --format template --template "@/usr/local/share/trivy/templates/html.tpl" -o /tmp/pipeline-report/trivy-pipeline${BUILD_NUMBER}-report.html --exit-code 0 --severity HIGH,CRITICAL ${ImageRegistry}/devsecops:v${BUILD_NUMBER}')
            }
        }
        stage('Push Image to nexus') {
            steps {
                sh('echo "$REGISTRY_CRED_PSW" | docker login $ImageRegistry -u $REGISTRY_CRED_USR --password-stdin')
                sh('docker push $ImageRegistry/devsecops:v${BUILD_NUMBER}')
                sh('docker rmi $ImageRegistry/devsecops:v${BUILD_NUMBER}') 
            }
        }
        stage('Deploy app to Staging env') {
            steps {
                sh('cd app/py-sample/deploy/manifest')
                sh('oc login --token=$CLUSTER_TKN --server=$OcpCluster')
                sh('oc project $ocpProject && oc create $manifestFile')
                sh('sleep 30s && oc get all')
            }
        }
        stage('Zap Proxy - Dynamic application security testing process') {
            steps {
                    sh """
                    docker run --rm -v /zap:/zap/wrk:rw -v /opt/hosts_zap:/etc/hosts -t ictu/zap2docker-weekly zap-baseline.py -I -j \
                    -t http://$appEndpoint \
                    -r reportzap.html \
                    -J reportzap.json \
                    -g reportzap.conf \
                    --hook=/zap/auth_hook.py \
                    -z "auth.loginurl=http://$appEndpoint/login \
                        auth.username="user" \
                        auth.password="password""
                    mkdir /var/www/html/zapReport/pipeline${BUILD_NUMBER}/
                    cp /zap/* /var/www/html/zapReport/pipeline${BUILD_NUMBER}/
                    rm -rf /zap/*
                    """
            }
        }
        stage('Clean up cred') {
            steps {
                sh('docker logout')
                sh('oc logout')
            }
        }
    }
}