pipeline {
    agent any
    stages {
        stage('Check manifest file') {
            steps {
                    sh '''
                    cd app/deploy/manifest
                    ls -la
                    '''
            }
        }
        stage('Check ocp status') {
            steps {
                    sh '''
                    ls -la
                    oc login -u $ocpUser -p $ocpPassword --server=https://api.lab.i3datacenter.my.id:6443
                    oc whoami
                    oc project $ocpProject
                    oc project
                    '''
            }
        }
    }
}